### ISSUE TITLE
skin retouching

### ISSUE THREAD

**Issue by devriesewouter89** [luca-arts/seeingtheimperceptible#12]
implement test of skin retouching

**Comment by devriesewouter89** [comment]
1. retouchML
2. Face Smoothing

**Comment by lvn27** [comment]
Face smoothing Is done. retouchML needs some more testing

**Comment by devriesewouter89** [comment]
retouchML: where is the model adapted (in code?)

**Comment by lvn27** [comment]
Face Smoothing : blur amount is situated in folder "configs -> configs.yaml" under filter -> sigma_1: 50  | sigma_2: 50.
is it possible to have a slider for those two sigma values so we can add more or less blur to the images.

**Comment by lvn27** [comment]
* the configs folder is situated in the forked "face-smoothing" code.

**Comment by devriesewouter89** [comment]
Sliders have been added to the notebook
