### ISSUE TITLE
verify quality of super resolution

### ISSUE THREAD

**Issue by devriesewouter89** [luca-arts/seeingtheimperceptible#25]

**Comment by devriesewouter89** [comment]
the notebook for superResolution downsamples an image and then restores it via a ESRGAN model.
Verify if the quality of the restored image is of good quality.

**Comment by lvn27** [comment]
I tested the ESRGAN (Super Resolution) and the BasicSR (real-ESRGAN) models. 
- ESRGAN : this model was a downscaling and afterwards an upscaling. the result wasn't good.
- BASICSR : this model was only an upscaling and the result was decent. 
- EDSR : this model gives more or less the best result

the Super Resolution with OpenCV can also be tested with other models, like FSRCNN
