### ISSUE TITLE
combine research Q 1 and 3

### ISSUE THREAD

**Issue by devriesewouter89** [luca-arts/seeingtheimperceptible#26]

**Comment by lvn27** [comment]
momenteel kan ik niets pushen naar de github - hierdoor schrijf ik even mijn gecombineerde onderzoeksvraag: 

How can we integrate open-source machine learning models within the current workflow of photographers, and set these models to work to free lens-based creatives of repetitive and labour-intensive tasks?

ik denk dat dit wel klopt als één geheel van de 2 combi's
