### ISSUE TITLE
bevraging

### ISSUE THREAD

**Issue by devriesewouter89** [luca-arts/seeingtheimperceptible#9]
1. reminder sturen indien nog niet veel antwoorden
2. tussentijdse inzichten noteren/er uit halen

**Comment by devriesewouter89** [comment]
tussentijdse OK, binnen enkele weken nog eens finaal verslag trekken.

**Comment by lvn27** [comment]
de beroepsvereniging van fotografen hebben eindelijk gereageerd en gaan het hopelijk doorsturen naar hun leden.
